### ISSUE TITLE
error messages are not useful for debugging

### ISSUE THREAD

**Issue by shime** [machty/emblem.js#190] opened 2015-01-15 13:42 UTC
This is the template being used
```haml
.container
  .main
    .post-wrapper

  select
    option(val="") Color
    option value="Blue" Blue
    option value="Red" Red
```

The error reported will have cryptic message, unrelated to the source of the problem
```shell
Emblem syntax error, line 2: Expected BeginStatement or DEDENT but "\uEFEF" found.
  .main
^
```

**Comment by ziggythehamster** [comment] 2015-01-28 19:15
Isn't this a duplicate of #180?

**Comment by thec0keman** [comment] 2016-05-09 05:14
Moved to #276

**Closed by thec0keman** 2016-05-09 05:14 UTC
